### ISSUE TITLE
Installing from git repo runs install on every Puppet run

### ISSUE THREAD

**Issue by Yuav** [voxpupuli/puppet-python#193]
$ pip install -e git+https://github.com/dcramer/piplint.git#egg=piplint-dev
$ pip freeze | grep piplint
-e git://github.com/dcramer/piplint.git@c1c7921784d0315b659e0b53a2752ee5f0d202fe#egg=piplint-dev

The current check use regex: ^piplint==, which correlates to:
piplint==0.1.1

And as such, the module determines that piplint isn't installed, and starts install again

**Comment by Yuav** [comment]
Same issue as with the pip provider:

https://tickets.puppetlabs.com/browse/PUP-2905

**Comment by dvorak** [comment]
Having the same problem, and it's causing services to restart every time puppet runs.
