### ISSUE TITLE
So many Warnings

### ISSUE THREAD

**Issue by sunil592002** [voxpupuli/puppet-python#351]
Warning: Scope(Class[Python::Install]): Could not look up qualified variable '::python::version'; class ::python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::version'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::dev'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::dev'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::pip'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::pip'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::virtualenv'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::virtualenv'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::ensure'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::provider'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::use_epel'; class python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable '::python::version'; class ::python has not been evaluated
Warning: Scope(Class[Python::Install]): Could not look up qualified variable 'python::manage_gunicorn'; class python has not been evaluated

**Comment by juniorsysadmin** [comment]
Closing, quite certain that this does not affect recent versions
