### ISSUE TITLE
scl repo returning 404

### ISSUE THREAD

**Issue by wyardley** [voxpupuli/puppet-python#353]
With code like:
```
  class { '::python':
    provider => 'rhscl',
    version  => 'rh-python34',
    use_epel => false,
  } 
```
I currently am getting the error:

```
Error: Execution of '/bin/rpm -i https://www.softwarecollections.org/en/scls/rhscl/rh-python34/epel-7-x86_64/download/rhscl-rh-python34-epel-7-x86_64.noarch.rpm' returned 1: curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://www.softwarecollections.org/en/scls/rhscl/rh-python34/epel-7-x86_64/download/rhscl-rh-python34-epel-7-x86_64.noarch.rpm - transfer failed
Error: /Stage[main]/Python::Install/Package[rhscl-rh-python34-epel-7-x86_64]/ensure: change from absent to present failed: Execution of '/bin/rpm -i https://www.softwarecollections.org/en/scls/rhscl/rh-python34/epel-7-x86_64/download/rhscl-rh-python34-epel-7-x86_64.noarch.rpm' returned 1: curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://www.softwarecollections.org/en/scls/rhscl/rh-python34/epel-7-x86_64/download/rhscl-rh-python34-epel-7-x86_64.noarch.rpm - transfer failed
```
For CentOS, if I install the release file by hand as documented at https://www.softwarecollections.org/en/scls/rhscl/rh-python34/, I get something like:
http://mirror.centos.org/centos/7/sclo/x86_64/rh/python34/

I don't know what the behavior should be and whether RH and CentOS should have the same behavior for installing SCL; I can work on a PR to fix this if you can give me some ideas about what the behavior should be like. I'm thinking of doing something like this as a workaround:
```
  package { 'centos-release-scl':
    ensure => present,
  } ->
  class { '::python':
    provider                    => 'rhscl',
    version                     => 'rh-python34',
    use_epel                    => false,
    rhscl_use_public_repository => false,
  } -> 
```
It also seems like there's now a python35 scl, this one is prefixed with 'rh' (rh-python35) vs just python34 for 3.4 (in the repo path, not the package name itself)

**Comment by wyardley** [comment]
ps: after satisfying the dep as outlined above, I'm getting this error until adding `virtualenv                  => present`:

```
Error: Execution of '/bin/rpm -e rh-python34-python-virtualenv-1.11.6-1.el7.noarch' returned 1: error: Failed dependencies:
	rh-python34-python-virtualenv is needed by (installed) rh-python34-2.0-5.el7.x86_64
Error: /Stage[main]/Python::Install/Package[virtualenv]/ensure: change from 1.11.6-1.el7 to absent failed: Execution of '/bin/rpm -e rh-python34-python-virtualenv-1.11.6-1.el7.noarch' returned 1: error: Failed dependencies:
	rh-python34-python-virtualenv is needed by (installed) rh-python34-2.0-5.el7.x86_64
```

**Comment by MBetters** [comment]
Were you able to solve this? I'm currently having the same issue. Thanks.

**Comment by wyardley** [comment]
@MBetters TBH, I don't remember, haven't needed to do this recently.

**Comment by Skarzee** [comment]
I had a similar issue to this regarding the usage of rhscl against scl (centos vs rh). I got 404s using rhscl as the provider also, and therefore believe this is still an issue. At present, the 'scl' provider is available within code, but not mentioned at all in the documentation.
