### ISSUE TITLE
Activity on this project?

### ISSUE THREAD

**Issue by chgarling** [voxpupuli/puppet-python#371]
Hi there,

is this project still active? The python::virtualenv class does not work at least on CentOS 7, I already provided a PR to potentially fix this issue, but got no response.

Regards, Christian

**Comment by Mears148** [comment]
I have not seen any movement on this either....I would check your build status on your PR however. The change you made failed the spec_helper test. Maybe you will get movement if that gets solved first.

I agree though....the --no-use-wheel option needs to be replaced if this is going to continue to function. Thanks for the PR.

**Comment by flokli** [comment]
@chgarling I think this can be closed now.

**Comment by ghoneycutt** [comment]
We really need acceptance testing with Beaker. Given all the various platforms and versions of python, it is difficult to review and merge changes without this ability to functionally test. Any help in that area would be greatly appreciated.

**Comment by chgarling** [comment]
Hi,
any plans when the new release will be there? We are still waiting for the fixes to come.
Best regards, Christian

**Comment by fnoop** [comment]
I have some updates but not going to waste time submitting PRs when they're being ignored.  Perhaps time to fork this module into voxpopuli?

**Comment by craig** [comment]
Yea, that sounds like a good idea.

**Comment by stankevich** [comment]
I haven't worked on or contributed to this project in a while. Any help to maintain it is appreciated. Any volunteers?

**Comment by gdubicki** [comment]
Thanks for replying @stankevich . Can you please move this project under voxpupuli?

**Comment by bostrowski13** [comment]
It would be great to see voxpupuli take this over.  Really like to use this for a lot of projects.

**Comment by stankevich** [comment]
This project has been moved under voxpupuli: https://github.com/voxpupuli/puppet-python
