### ISSUE TITLE
audit metaparameter is deprecated

### ISSUE THREAD

**Issue by sfinke0** [voxpupuli/puppet-python#375]
Hi,

the following warning occurred on my systems:

```
The `audit` metaparameter is deprecated and will be ignored in a future release.
```

Would you please fix this in an upcoming release?

cheers,
carazzim0

**Comment by FlorianSW** [comment]
The easiest fix seems to be to revert https://github.com/stankevich/puppet-python/commit/7aeaeceda55733767bf357968b3ea4fddef1bd53?

**Comment by bruhadavid** [comment]
Is there an ETA for this?

**Comment by JvGinkel** [comment]
Why not just remove the audit metaparameter from the file resource?

**Comment by smortex** [comment]
This issue is now invalid: the deprecated has been removed and the behavior is still supported:
https://tickets.puppetlabs.com/browse/PUP-8113

This issue can be closed.
