### ISSUE TITLE
Can't install this using librarian-puppet

### ISSUE THREAD

**Issue by mpdude** [voxpupuli/puppet-python#406]
I tried to install this using `librarian-puppet` and assumed the name would be `puppet-python` as per the `metadata.json`.

However, `librarian-puppet` complains 

>  Unable to find module 'puppet-python' on https://forgeapi.puppetlabs.com

Additionally, I found that the link provided in the README to the Puppet forge (https://forge.puppet.com/puppet/python) is broken.

So, maybe something went wrong when moving this package?

**Comment by mpdude** [comment]
You can use a `:git` URL with `librarian-puppet` as a workaround.

**Comment by bastelfreak** [comment]
We just didn't release it to the forge yet. This will happen in the next few days.

**Comment by mpdude** [comment]
Thanks!

Maybe you could keep this open as a reminder :-) and close once it has been released.

**Comment by darthsteven** [comment]
It's on the forge now 👍 

This issue can be closed!
