### ISSUE TITLE
Support for Python3.6 executables

### ISSUE THREAD

**Issue by pscadiz** [voxpupuli/puppet-python#420]
Just leaving a question here.
Am currently experiencing setting up python+virtualenv using python3.6
Have installed it through the epel repositories, which has given the executable /bin/python36

Now setting up virtual environments through python3.6 no longer uses the virtualenv pip package, instead it can be set up using the command /bin/python36 -m venv /path/to/virtualenv.

Here's what I have experienced so far:
- python::virtualenv does not work because of the exec resource it tries to invoke
- python::pip, including the virtualenv parameter does not make any change at all

Is there any implementation if the latest version of this module to support it?
Just leaving a question here.

Operating system used - CentOS7
Puppet version - Puppet4
Module version used - v2.1.0 (used the tag)

**Comment by bastelfreak** [comment]
Hi @pscadiz.
This is currently not supported. Are you able to provide a PR for this?

**Comment by pscadiz** [comment]
Hi @bastelfreak 

Will work on it, among other things I still owe you :)

Thanks!

**Comment by danquack** [comment]
Hey @pscadiz, I’m curious if maybe I’m misunderstanding you. But using the rscl libraries I was able able to create a virtual environment and install pip packages, utilizing 2.1. Are you experiencing different? I have this with both CentOS and RHEL. Maybe I can provide how, but just want to make sure I’m understanding you properly.
