### ISSUE TITLE
Impossible to use version number in Ubuntu 16.04

### ISSUE THREAD

**Issue by golinko** [voxpupuli/puppet-python#448]
- Puppet: 5.5.2
- Ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
- Distribution: Ubuntu 16.04.2 LTS
- Module version: v2.2.2

I want to make puppet install python3 on a host and use pip3 provider

##  My manifest:
```puppet
 class { 'python':
    ensure => 'present',
    version => '3',
    pip     => 'latest',
  }
  python::pip { $package_id:
    ensure       => 'latest',
    pkgname      => $package_name,
    pip_provider => 'pip3',
  }
```
##  puppet run output error
```
Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install 3' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package 3
Error: /Stage[main]/Python::Install/Package[python]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install 3' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package 3
```

If I try to use 
```puppet
version => 'python3'
``` 
I get:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, version needs to be within[system, pypy, 3, 3.3, 2.7]
``` 

Is it a bug or I miss something here?

I am new to puppet but I am just wondering when I will meet the condition here: https://github.com/voxpupuli/puppet-python/blob/f274e51ffdf53c5f17d468053d27977c586ae8ef/manifests/install.pp#L236

**Comment by jradmacher** [comment]
I hit the same problem. To me it looks like two bugs:
- version expects(= checks for) numbers, but does not add 'python' to the package name
- the version list is hard coded per OS, so every version bump by the distribution requires updating this list. Also, custom repositories cannot be used, if they add "unexpected" python versions

**Workaround:**
```
 class { 'python':
    ensure => 'present',
    version => 'python3',
    valid_versions => 'python3',
    pip     => 'latest',
  }
```
YAML:
```
python::version: 'python3'
python::valid_versions: 'python3'
```
