### ISSUE TITLE
Variable $subscribe shoud not be overwritten

### ISSUE THREAD

**Issue by seocam** [voxpupuli/puppet-python#470]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2
- Ruby: 2.3.3
- Distribution: Debian GNU/Linux 9.5 (stretch)
- Module version: 2.2.2

## How to reproduce (e.g Puppet code you use)
```puppet
python::requirements { '/tmp/requirements.txt':
    virtualenv => $venv_directory,
    subscribe  => Vcsrepo[$app_directory],
    require    => Python::Pyvenv[$venv],
}
```

## What are you seeing 

I cannot make any of my instances of `python::requirements`  subscribe to other resources because inside of puppet-python `requirements.pp` the `$subscribe` variable (meta variable of puppet) is overwritten. 

## What behaviour did you expect instead

I'd expect to be able to subscribe to a resource. Renaming `$subscribe` inside `requirements.pp` to something else would probably be enough. 

Because of that I had to keep `stankevich-python` instead of updating it to voxpupuli version.

## Output log
```log
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Cannot reassign variable '$subscribe' at /etc/puppet/modules/python/manifests/requirements.pp:134:16 at /etc/puppet/modules/profile/manifests/api.pp:151 on node 2950a0e0-flower.2950a0e0
```

**Comment by wilrodriguez** [comment]
We also are running into this issue. It's not just you. I am greatly saddened.

**Comment by nward** [comment]
I've hit this too, I've fired through a PR to fix. Should be a trivial one I think.
