### ISSUE TITLE
Python 3.6 on ubuntu 18.04 not working

### ISSUE THREAD

**Issue by rismoney** [voxpupuli/puppet-python#508]
I am trying to use this python module (latest) to install python 3.6 on an ubuntu 18.04

```puppet
class { 'python':
    version    => '3.6',
    pip        => 'present',
    dev        => 'present',
    virtualenv => 'present',
  }
```

No virtualenv installed on path - can't create environments.
Please advise on what I am doing wrong.

**Comment by tonythomas01** [comment]
Happening for me on 3.7 as well. A simple `sudo apt-get install python3.7` on the machine works though. Very interesting what is going on.

**Comment by baurmatt** [comment]
This broke in https://github.com/voxpupuli/puppet-python/pull/489
