### ISSUE TITLE
Can't uninstall pip package because of duplicate variable name

### ISSUE THREAD

**Issue by bdelamatre** [voxpupuli/puppet-python#532]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.17
- Ruby:
- Distribution:
- Module version: 3.0.1

## How to reproduce (e.g Puppet code you use)
Try uninstalling any pip package

## What are you seeing
 Evaluation Error: Cannot reassign variable '$pip_exec_name' (file: /etc/puppetlabs/code/environments/development/vendor-modules/python/manifests/pip.pp, line: 224, column: 24) (file: /etc/puppetlabs/code/environments/development/modules/profile/manifests/base/python/supervisor.pp, line: 7)

## What behaviour did you expect instead
pip package to be uninstalled

## Any additional information you'd like to impart
$pip_exec_name is defined on both lines 177 and 224

**Comment by apeeters** [comment]
Fixed in https://github.com/voxpupuli/puppet-python/commit/94d62184eb856beb933738ba6a30b26f8b593223 released as v4.0.0.
