### ISSUE TITLE
Only supports CentOS, no other derivatives

### ISSUE THREAD

**Issue by bigon** [voxpupuli/puppet-python#650]
Hello,

It seems that the module [only supports CentOS](https://github.com/voxpupuli/puppet-python/blob/master/manifests/install.pp#L38) out of the box and not the other derivatives like AlmaLinux

There seems to be an easy workaround for this, I guess the module still should be updated to support other derivatives

**Comment by d1nuc0m** [comment]
@bigon No, derivatives such report RedHat as family, try to run `/usr/bin/facter os.family` on AlmaLinux or Rocky Linux

**Comment by bigon** [comment]
Hello @d1nuc0m 

At the time of my bug, this was the content of the file: https://github.com/voxpupuli/puppet-python/blob/b78b4c97fb89db765ca54fad2a084645f597b11e/manifests/install.pp#L38

This has already been fixed in https://github.com/voxpupuli/puppet-python/commit/92b91a0683c52d6b43f8c4579764c99054a9af0e

**Comment by d1nuc0m** [comment]
> Hello @d1nuc0m
> 
> At the time of my bug, this was the content of the file:
> 
> https://github.com/voxpupuli/puppet-python/blob/b78b4c97fb89db765ca54fad2a084645f597b11e/manifests/install.pp#L38

Sorry, didn't notice that - and thank you
